# permissions for end users to view clustersecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustersecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: resource-mirror
    app.kubernetes.io/part-of: resource-mirror
    app.kubernetes.io/managed-by: kustomize
  name: clustersecret-viewer-role
rules:
- apiGroups:
  - resourcemirror.joshault.dev
  resources:
  - clustersecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resourcemirror.joshault.dev
  resources:
  - clustersecrets/status
  verbs:
  - get
